### ISSUE TITLE
v0.4 not released properly

### ISSUE THREAD

**Issue by rider-yi** [vivri/Adjective#2]
```scala
@ import $ivy.`com.victorivri::adjective:0.4`
import $ivy.$

@ import com.victorivri.adjective._
cmd2.sc:1: object victorivri is not a member of package com
import com.victorivri.adjective._
           ^
Compilation Failed
```

![スクリーンショット 2019-06-05 21 31 30](https://user-images.githubusercontent.com/8375652/58956455-5a0d8800-87d9-11e9-8fd9-ffe3aa191590.png)

**Comment by vivri** [comment]
Thanks @rider-yi! I'm still pretty new to publishing in Sonatype Nexus.

This is fixed for `0.4.4` - also it cross-compiles to JS.
